Finish exercises
Maarcfleckk/Javascript-functions pull request #1
Opened 2023-11-18 18:07 UTC by Maarcfleckk

Exercises have been finished and ready for a review.

2023-11-19 20:16 UTC, tictools requested changes

2023-11-19 20:16 UTC, tictools commented on exercise_02/getTotalWordsFromString.js
> +    console.log("It must be a String");
Nice validation! But this will not properly work.
What will happen if passed argument is not a string? It will be logged "It must be a String" and code flow will keep executing until one `return` is found.

Have you tested it? 🤔

FIX: needs work

2023-11-19 20:16 UTC, tictools commented on exercise_03/generateRandomNumberInRange.js
> +    console.log("Input must be a number");
Same here: you are logging the error, but execution will continue until next `return`.

Have you tested it? 🤔

FIX: needs work

2023-11-19 20:16 UTC, tictools commented on exercise_04/isGreaterThan.js
> +    console.log("Input must be a number");
Same here: you are logging the error, but execution will continue until next return.

Have you tested it? 🤔

FIX: needs work

2023-11-19 20:16 UTC, tictools commented on exercise_05/isAdditionGreaterThanFifty.js
> +  if (typeof summand1 !== "number" || typeof summand2 !== "number") {
Same here: you are logging the error, but execution will continue until next return.

Have you tested it? 🤔

FIX: needs work

2023-11-19 20:16 UTC, tictools commented on exercise_06/checkCollectionHasElements.js
> +    console.log("Input must be an array");
Same here: you are logging the error, but execution will continue until next return.

Have you tested it? 🤔

FIX: needs work

2023-11-19 20:16 UTC, tictools commented on exercise_07/isTypeOf.js
> +  if (type === Array.isArray() && Array.isArray(valueToBeChecked)) return true;
This conditional statement is wrong. it will not work.

Have you tested it? 🤔

FIX: needs work

2023-11-20 19:14 UTC, yasirelbouazzati requested changes

2023-11-20 19:14 UTC, yasirelbouazzati commented on exercise_04/index.js
> +import isGreaterThan from "./isGreaterThan.js";
in my opinion take care of the spaces . You have the same problem in almost all exercice

2023-11-21 07:15 UTC, tictools requested changes

2023-11-21 07:15 UTC, tictools commented on exercise_02/getTotalWordsFromString.js
> +  let filteredWords = words.filter((word) => word.length > 0);
This is not necessary. You can remove this line and directly return `words.length`

FIX: needs work

2023-11-21 07:15 UTC, tictools commented on exercise_04/isGreaterThan.js
FIX: needs work

2023-11-21 07:15 UTC, tictools commented on exercise_06/checkCollectionHasElements.js
FIX: needs work

2023-11-21 16:46 UTC, tictools approved these changes

2023-11-21 17:38 UTC, yasirelbouazzati approved these changes

2023-11-21 17:45 UTC, yasirelbouazzati approved these changes

2023-11-21 18:38 UTC, yasirelbouazzati approved these changes
done!

2023-11-21 18:40 UTC, merged